iMenyn.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using iMenyn.Data.Abstract;
using iMenyn.Data.Abstract.Db;
using iMenyn.Data.Attributes;
using iMenyn.Data.Concrete;
using iMenyn.Data.Helpers;
using iMenyn.Data.Models;
using iMenyn.Web.Areas.Admin.ViewModels;
using iMenyn.Web.Helpers;
using iMenyn.Web.ViewModels;

namespace iMenyn.Web.Controllers
{
    [Authorize]
    public class AdminController : BaseController
    {
        public AdminController(IDb db, ILogger logger)
            : base(db, logger)
        {
        }

        public ActionResult Index()
        {
            var viewModel = new DashboardViewModel
            {
                NewEnterprises = new List<Enterprise>(),
                ModifiedEnterprises = new List<Enterprise>(),
                Account = AccountViewHelper.ModelToViewModel(CurrentAccount)
            };

            if (CurrentAccount.IsAdmin)
            {
                var modifiedAndNewEnterprises = Db.Enterprises.GetModifiedAndNewEnterprises().ToList();

                var newEnterprises = modifiedAndNewEnterprises.Where(e => e.IsNew);
                var modifiedEnterprises = modifiedAndNewEnterprises.Where(e => e.LockedFromEdit);

                viewModel.NewEnterprises = newEnterprises.ToList();
                viewModel.ModifiedEnterprises = modifiedEnterprises.ToList();
                viewModel.AllEnterprises = Db.Enterprises.GetAllEnterprises().OrderBy(e => e.Name);

                viewModel.ProductCount = Db.Products.ProductTotalCount();
            }
            else
            {
                //if (CurrentAccount.Enterprise == null)
                //{
                //    return View(model);
                //}

                //var enterprise = Repository.GetEnterpriseById(CurrentAccount.Enterprise);

                //if (enterprise.Menu != null)
                //{
                //    var menu = Repository.GetMenuById(enterprise.Menu);
                //    var products = Repository.GetProducts(menu.Products.ToList());

                //var s = ViewModelHelper.CreateStandardViewModel(enterprise, products);
                //model.StandardViewModel = s;
                //}
            }
            return View(viewModel);
        }

        [AdminOnly]
        public ActionResult Accounts()
        {
            //TODO
            //var accounts = Repository.GetAccounts().Where(a => a.IsAdmin != true);
            //ViewBag.Accounts = accounts;
            return null;
        }

        public ActionResult Log()
        {
            return View();
        }

        [AdminOnly]
        public ActionResult Settings()
        {
            return null;
        }

        [AdminOnly]
        public ActionResult CreateAllIndexes()
        {
            RavenContext.Instance.CreateAllIndexes();
            return RedirectToAction("Index");
        }


        [AdminOnly]
        public ActionResult MenuApproval(string enterpriseId)
        {
            var enterpriseViewModel = Db.Enterprises.GetCompleteEnterprise(enterpriseId, true);
            if (enterpriseViewModel.Enterprise.IsNew || enterpriseViewModel.Enterprise.LockedFromEdit)
                return View(enterpriseViewModel);

            return RedirectToAction("Index");
        }

        [AdminOnly]
        public RedirectToRouteResult MenuApprovalFunction(string enterpriseId, bool approved)
        {
            var enterprise = Db.Enterprises.GetEnterpriseById(enterpriseId);

            //Approve new menu
            if (approved && enterprise.IsNew)
            {
                enterprise.IsNew = false;
                Db.Enterprises.UpdateEnterprise(enterprise);
                Logger.Info("New enterprise approved: {0} ({1}), Code:[ccxcd77mnm]", enterprise.Name, enterpriseId);
            }

            //Disapprove new menu
            if (!approved && enterprise.IsNew)
            {
                Db.Enterprises.DeleteEnterprise(enterprise.Id);
            }

            //Approve modified menu
            if (approved && enterprise.LockedFromEdit && !enterprise.IsNew)
            {
                Db.Enterprises.SetModifiedMenuAsDefault(enterpriseId);
            }
            //Disapprove modified menu
            if (!approved && enterprise.LockedFromEdit && !enterprise.IsNew)
            {
               Db.Enterprises.DisapproveModifiedMenu(enterpriseId);
            }

            return RedirectToAction("Index");
        }

        [AdminOnly]
        [HttpPost]
        public ActionResult AddAccount(AccountViewData account)
        {
            if (account.UserInput.Password != account.UserInput.ConfirmPassword)
            {
                ModelState.AddModelError("ConfirmPassword", "Lösenorden matchar inte!");
            }
            if (ModelState.IsValid)
            {
                var newAccount = new Account
                                  {
                                      Id = AccountHelper.GetId(account.UserInput.Email),
                                      Email = account.UserInput.Email,
                                      Enabled = true,
                                      IsAdmin = false,
                                      Name = account.UserInput.Name,
                                  };
                newAccount.SetPassword(account.UserInput.Password);
                //Repository.AddAccount(newAccount);
            }

            //TODO
            //var accounts = Repository.GetAccounts().Where(a => a.IsAdmin != true);
            //ViewBag.Accounts = accounts;

            return null;
        }

        [AdminOnly]
        public RedirectToRouteResult DeleteEnterprise(string enterpriseId)
        {
            Db.Enterprises.DeleteEnterprise(enterpriseId);
            return RedirectToAction("Index");
        }

        #region Create fake enterprise
        [AdminOnly]
        public RedirectToRouteResult CreateFakeEnterprise(bool modified)
        {
            FakeDataHelper.CreateFakeEnterprise(Db, modified);
            return RedirectToAction("Index");
        }
        #endregion

        [AdminOnly]
        public JsonResult GetLogList(string query, bool info, bool debug, bool error, bool fatal, bool warn)
        {
            var loglist = Logger.GetLogList(query, info, debug, error, fatal, warn);
            return Json(loglist);
        }

    }
}

iMenyn.Web/Controllers/CabaretController.cs
using System.Web.Mvc;
using iMenyn.Data.Abstract;
using iMenyn.Data.Abstract.Db;
using iMenyn.Data.Helpers;

namespace iMenyn.Web.Controllers
{
    public class CabaretController : BaseController
    {
        public CabaretController(IDb db, ILogger logger)
            : base(db, logger) { }

        public ActionResult Index(string q)
        {
            if (!string.IsNullOrEmpty(q))
            {
                var enterprise = Db.Enterprises.GetCompleteEnterprise(EnterpriseHelper.GetId(q));
                return View(enterprise);
            }
            return RedirectToAction("Index","Home");
        }

        public ActionResult Product(string id)
        {
            //TODO
            //var product = Repository.GetProductById(id);
            //ViewBag.Product = product;
            return View();
        }


    }
}

iMenyn.Web/Views/Admin/Index.cshtml
@using iMenyn.Data.Helpers
@model iMenyn.Web.ViewModels.DashboardViewModel

@{
    ViewBag.Title = "Hantera";
}

<h2>Välkommen @Model.Account.Name</h2>

@if (Model.Account.IsAdmin)
{
    <div class="row">
        <div class="col-sm-12">
            <a href="@Url.Action("CreateFakeEnterprise", new { modified = false })" class="btn btn-primary">Skapa fake-enterprise (ny)</a>
            <a href="@Url.Action("CreateFakeEnterprise", new { modified = true })" class="btn btn-primary">Skapa fake-enterprise (modifierad)</a>
            <a href="@Url.Action("CreateAllIndexes")" class="btn btn-primary">Återskapa index</a>
        </div>
    </div>
    <div class="col-sm-6 well">
        <h4>Nya restauranger <small>(@Model.NewEnterprises.Count)</small></h4>
        @if (Model.NewEnterprises.Count == 0)
        {
            <i>Inga...</i>
        }
        else
        {
            <ul class="list-group">
                @foreach (var enterprise in Model.NewEnterprises.Take(5))
                {
                    <li class="list-group-item">
                        <a href="@Url.Action("MenuApproval", new { enterpriseId = enterprise.Id })">
                            <h3 class="list-group-item-heading">@enterprise.Name</h3>
                            <p class="list-group-item-text">
                                Produkter: @if (enterprise.Menu != null && enterprise.Menu.Categories != null)
                                           {
                                    @enterprise.Menu.Categories.SelectMany(c => c.Products).Count()
                                           }
                                           else
                                           {
                                    <span>Inga</span>
                                           }<br />
                                Inkommen: @enterprise.LastUpdated.ToShortDateString() (@enterprise.LastUpdated.ToShortTimeString())
                            </p>
                        </a>
                    </li>
                }
            </ul>
        }
    </div>
    <div class="col-sm-6 well">
        <h4>Modifierade menyer <small>(@Model.ModifiedEnterprises.Count)</small></h4>
        @if (Model.ModifiedEnterprises.Count == 0)
        {
            <i>Inga...</i>
        }
        else
        {
            <ul class="list-group">
                @foreach (var enterprise in Model.ModifiedEnterprises.Take(5))
                {
                    <li class="list-group-item">

                        <a href="@Url.Action("MenuApproval", new { enterpriseId = enterprise.Id })">

                            <h4 class="list-group-item-heading">@enterprise.Name</h4>
                            Uppdaterad: @enterprise.LastUpdated.ToShortDateString() (@enterprise.LastUpdated.ToShortTimeString())
                        </a>
                    </li>
                }
            </ul>
        }
    </div>
    <div class="col-sm-12">
        <h1>Produkter</h1>
        <p>Totalt: @Model.ProductCount</p>
        <p>Snitt per restaurang: @(Model.ProductCount / Model.AllEnterprises.Count())</p>
    </div>
    <div class="col-sm-12">
        <h1>Restauranger <small>(@Model.AllEnterprises.Count())</small></h1>
        <ul class="list-group">
            @foreach (var e in Model.AllEnterprises)
            {
                <li class="list-group-item row">
                    <div class="row">
                        <div class="col-sm-11">
                            <div class="row nom">
                                <a href="@Url.Action("Index", "Cabaret", new { q = EnterpriseHelper.GetKey(e.Id) })" target="_blank"><strong>@e.Name</strong></a>
                                <span class="label label-info">
                                    @if (e.Menu != null && e.Menu.Categories != null)
                                    {
                                        @e.Menu.Categories.SelectMany(c => c.Products).Count()
                                    }
                                    else
                                    {
                                        <span>0</span>
                                    }
                                </span>
                                @if (e.IsNew)
                                {
                                    <span class="label label-warning ml5">Ny!</span>
                                }
                                @if (e.LockedFromEdit)
                                {
                                    <span class="label label-danger ml5">Låst</span>
                                }
                                @if (e.OwnedByAccount)
                                {
                                    <span class="label label-primary ml5">Ägd</span>
                                }
                            </div>
                            <div class="row nom">
                                @if(e.Coordinates != null)
                                {
                                    <small>Lat:@e.Coordinates.Lat, Lng:@e.Coordinates.Lng</small>
                                }
                            </div>
                        </div>
                        <div class="col-sm-1">
                            <a class="btn btn-danger pull-right" href="@Url.Action("DeleteEnterprise", "Admin", new { enterpriseId = e.Id })" onclick="return confirm('Really?');" >Radera<span class="glyphicon glyphicon-trash"></span></a>
                        </div>
                    </div>
                </li>   
            }
        </ul>
    </div>
}

iMenyn.Web/Views/Admin/Log.cshtml
@{
    ViewBag.Title = "Logg";
}

<h1>Logg</h1>

<div class="mt50">
    Sök:<input id="tb-query" type="text"/>
</div>                      

<div class="btn-group" data-toggle="buttons-checkbox">
    <button id="cb-info" class="btn active">Info</button>
    <button id="cb-debug" class="btn active">Debug</button>
    <button id="cb-warn" class="btn active">Warn</button>
    <button id="cb-error" class="btn active">Error</button>
    <button id="cb-fatal" class="btn active">Fatal</button>
</div>

<table class="table table-striped table-bordered margin-top">
    <thead>
        <tr>
            <th>Tidpunkt</th>
            <th>Meddelande</th>
            <th>Nivå</th>
        </tr>
    </thead>
    <tbody id="table-log-list">
        
    </tbody>
</table>

<script type="text/javascript">
    RenderLog();

    function RenderLog() {
        iMenyn.Admin.RenderLog('#table-log-list', $('#tb-query').val(), $('#cb-info').hasClass('active'), $('#cb-debug').hasClass('active'), $('#cb-error').hasClass('active'), $('#cb-fatal').hasClass('active'), $('#cb-warn').hasClass('active'));
    }
</script>

iMenyn.Web/Views/Admin/MenuApproval.cshtml
@model iMenyn.Data.ViewModels.CompleteEnterpriseViewModel

@{
    ViewBag.Title = "Ny meny";
    ViewBag.IsEdit = true;
}
<div class="well">
    <strong>IsNew</strong>: @Model.Enterprise.IsNew<br/>
    <strong>ModifiedMenu</strong>: @Model.Enterprise.ModifiedMenu<br/>
    <strong>Sökord</strong>:
        @foreach (var searchTag in Model.Enterprise.SearchTags)
        {
            <span>@searchTag, </span>
        }
    
</div>
@Html.Partial("~/Views/Partials/Menu/Edit/_Menu.cshtml", Model)

@Html.ActionLink("Godkänn", "MenuApprovalFunction", "Admin", new { enterpriseId = Model.Enterprise.Id, approved = true }, new { @class = "btn btn-success" })
@Html.ActionLink("Godkänn ej", "MenuApprovalFunction", "Admin", new { enterpriseId = Model.Enterprise.Id, approved = false }, new { @class = "btn btn-danger", onclick = "return confirm('Vill du verkligen ta bort detta bidrag?');" })